=== at0529/XSD-XML/src/main/resources/Customer.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/Customer" xmlns:tns="http://www.example.org/Customer" elementFormDefault="qualified">



    <complexType name="Customer">
    	<sequence>
    		<element name="customerId" type="int"></element>
    		<element name="name" type="string"></element>
    		<element name="dateOfBirth" type="date"></element>
    		<element name="annualSalary" type="double"></element>
    		<element name="address" type="tns:Address"
    			maxOccurs="unbounded" minOccurs="1">
    		</element>
    		<element name="payment" type="tns:PaymentMethod" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>
    

    <complexType name="PaymentMethod">
    	<sequence>
    		<element name="cardNumber" type="long"></element>
    		<element name="cardName" type="string"></element>
    		<element name="dateFrom" type="date"></element>
    		<element name="dateTo" type="date"></element>
    		<element name="card" maxOccurs="1" minOccurs="1">
    			<simpleType>
    				<restriction base="string">
    					<enumeration value="CREDIT CARD"></enumeration>
    					<enumeration value="DEBIT CARD"></enumeration>
    				</restriction>
    			</simpleType>
    		</element>
    	</sequence>
    </complexType>


    <complexType name="Address">
    	<sequence>
    		<element name="streetName" type="string"></element>
    		<element name="city" type="string"></element>
    		<element name="state" type="string"></element>
    		<element name="pinCode" type="string"></element>
    	</sequence>
    </complexType>

    <element name="Customer" type="tns:Customer"></element>
</schema>

=== at0529/XSD-XML/src/main/resources/Customer.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Customer xmlns:tns="http://www.example.org/Customer" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Customer Customer.xsd ">
  <tns:customerId>0</tns:customerId>
  <tns:name>tns:name</tns:name>
  <tns:dateOfBirth>2001-01-01</tns:dateOfBirth>
  <tns:annualSalary>0.0</tns:annualSalary>
  <tns:address>
    <tns:streetName>tns:streetName</tns:streetName>
    <tns:city>tns:city</tns:city>
    <tns:state>tns:state</tns:state>
    <tns:pinCode>tns:pinCode</tns:pinCode>
  </tns:address>
  <tns:payment>
    <tns:cardNumber>0</tns:cardNumber>
    <tns:cardName>tns:cardName</tns:cardName>
    <tns:dateFrom>2001-01-01</tns:dateFrom>
    <tns:dateTo>2001-01-01</tns:dateTo>
    <tns:card>CREDIT CARD</tns:card>
  </tns:payment>
</tns:Customer>
